<div class="footer-custom-links">
	<div class="popular_solutions">
		<h4>Popular Solutions</h4>
		<div>
			<ul class="footer links">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popular-solutions')->toHtml();?>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popular-solutions-business')->toHtml();?>
			
				
			</ul>
		</div>
	</div>
	<div class="alogic_business">
		<h4>Support</h4>
		<div>
			<ul class="footer links">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-section-footer')->toHtml();?>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-section-footer-business')->toHtml();?>
			
					
			</ul>
		</div>
	</div>
	<div class="support">
		<h4>Company</h4>
		<div>
		<ul class="footer links">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-section-footer')->toHtml();?>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-section-footer-business')->toHtml();?>
				
			</ul>
		</div>
	</div>
</div>
<div id="popup-container">
        <a class="close"></a>
          <div id="popup-window">
            <div class="modal-content">
			
            <div class="wdpu-head"> <div class="wdpu-title">Sign up today & receive 10% off your first order</div> <div class="wdpu-subtitle"></div> </div> 
			<div class="mform">
				<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="https://intesols.us7.list-manage.com/subscribe/post?u=ab7cfcdd75ce48742c1298640&amp;id=6daa0489df" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
	<label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
	<input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<label for="mce-FNAME">Full Name  <span class="asterisk">*</span>
</label>
	<input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ab7cfcdd75ce48742c1298640_6daa0489df" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->
			</div>
          </div>
        </div>
      </div>
		<link rel="stylesheet" href="<?php echo $block->getUrl() ?>pub/media/mpopup/style.css" />
		<script src="<?php echo $block->getUrl() ?>pub/media/mpopup/jquery.cookie.js"></script>
		<script src="<?php echo $block->getUrl() ?>pub/media/mpopup/custom.js"></script>

<script>
         jQuery(document).ready(function () {
			 var a = jQuery('.header.content').width();
			 var b = jQuery(window).width();
			 var c = b - a;			 
			 var m = c / 2;
			 jQuery('.menu > ul > li > ul').css('padding-left',m + 'px');
			 jQuery('.menu > ul > li > ul').css('padding-right',m + 'px');
		 });
		 
		 jQuery( window ).resize(function() {
			 var a = jQuery('.header.content').width();
			 var b = jQuery(window).width();
			 var c = b - a;			 
			 var m = c / 2;
			 jQuery('.menu > ul > li > ul').css('padding-left',m + 'px');
			 jQuery('.menu > ul > li > ul').css('padding-right',m + 'px');
		});
		 
</script>		  