<div class="footer-custom-links">
	<div class="popular_solutions">
		<h4>Popular Solutions</h4>
		<div>
			<ul class="footer links">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popular-solutions')->toHtml();?>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('popular-solutions-business')->toHtml();?>
			
				
			</ul>
		</div>
	</div>
	<div class="alogic_business">
		<h4>Support</h4>
		<div>
			<ul class="footer links">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-section-footer')->toHtml();?>
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('support-section-footer-business')->toHtml();?>
			
					
			</ul>
		</div>
	</div>
	<div class="support">
		<h4>Company</h4>
		<div>
		<ul class="footer links">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-section-footer')->toHtml();?>
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('company-section-footer-business')->toHtml();?>
				
			</ul>
		</div>
	</div>
</div> 
<script>
         jQuery(document).ready(function () {
			 var a = jQuery('.header.content').width();
			 var b = jQuery(window).width();
			 var c = b - a;			 
			 var m = c / 2;
			 jQuery('.menu > ul > li > ul').css('padding-left',m + 'px');
			 jQuery('.menu > ul > li > ul').css('padding-right',m + 'px');
		 });
		 
		 jQuery( window ).resize(function() {
			 var a = jQuery('.header.content').width();
			 var b = jQuery(window).width();
			 var c = b - a;			 
			 var m = c / 2;
			 jQuery('.menu > ul > li > ul').css('padding-left',m + 'px');
			 jQuery('.menu > ul > li > ul').css('padding-right',m + 'px');
		});
		 
</script>		 
<?php 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeID       = $storeManager->getStore()->getStoreId(); 
$storeName     = $storeManager->getStore()->getName();

if($storeID != 1) { ?>
	<style>
	.ves-container.home-section4, .ves-container.home-section5, .ves-container.home-section1 { display:block;  }
	.footer.links a[title="Blog"] { display: block; }
	</style>
<?php }

?>
