<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>
<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$current_category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$current_category->getLevel();
?>
<!--span style="display:none;"><?php echo $current_category->getChildrenCount() . 'jay' .$current_category->getLevel() ;?></span -->
<?php 
/* if($current_category->getChildrenCount() == 0 ) { */
if(($current_category->getLevel() == 5) || ($current_category->getLevel() == 4 && $current_category->getChildrenCount() == 0) ) {
?>
<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */ echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */ echo __('Shop By') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */ echo $block->getClearUrl() ?>" class="action clear filter-clear"><span><?php /* @escapeNotVerified */ echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php if ($filter->getItemsCount()): ?>
                    <?php if (!$wrapOptions): ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */ echo __('Filters') ?></strong>
                        <div class="filter-options " id="narrow-by-list" data-role="content" data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                    <?php  $wrapOptions = true; endif; ?>
					<?php  $attributeModel = $filter->getAttributeModel();	?>			
                  
					<?php 
					
					if($attributeModel) {
							$c =  $attributeModel->getAttributeCode();
						}  else {
							$c = '';
						}
						
						if($c == 'price')	{ 
						
						$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
						$scopeConfig = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');								
						//echo $price_scope = $objectManager->get('Magento\Framework\App\Config\ScopeConfigInterface')->getValue('intesolstheme/itprice/price');
						$scopeConfig = $scopeConfig->getValue("intesolstheme/itprice/price",\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
						?>
						<?php if($scopeConfig == "1"): ?>
						<div data-role="collapsible" class="filter-options-item <?php echo $c; ?>">
							<div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
							<div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
						</div>
					    <?php endif; ?>
						<?php } else { ?>
						
							<div data-role="collapsible" class="filter-options-item <?php echo $c; ?>">
								<div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */ echo __($filter->getName()) ?></div>
								<div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */ echo $block->getChildBlock('renderer')->render($filter); ?></div>
							</div>
							
						<?php } ?>
					
					
					
					
					
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions): ?>
                </div>
            <?php else: ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
<?php } ?> 