<?php
/**
 * @category   Intesols
 * @package    Intesols_Browsecatalogs
 * @author     jaimin.patel@intesols.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Intesols\Browsecatalogs\Block;

use Magento\Framework\View\Element\Template\Context;
use Intesols\Browsecatalogs\Model\BrowsecatalogsFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Browsecatalogs View block
 */
class BrowsecatalogsView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Browsecatalogs
     */
    protected $_browsecatalogs;
    public function __construct(
        Context $context,
        BrowsecatalogsFactory $browsecatalogs,
        FilterProvider $filterProvider
    ) {
        $this->_browsecatalogs = $browsecatalogs;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Intesols Browsecatalogs Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $browsecatalogs = $this->_browsecatalogs->create();
        $singleData = $browsecatalogs->load($id);
        if($singleData->getBrowsecatalogsId() && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}