<?php
/**
 * @category   Intesols
 * @package    Intesols_Browsecatalogs
 * @author     jaimin.patel@intesols.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Intesols\Browsecatalogs\Block;

use Magento\Framework\View\Element\Template\Context;
use Intesols\Browsecatalogs\Model\BrowsecatalogsFactory;
/**
 * Browsecatalogs List block
 */
class BrowsecatalogsListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Browsecatalogs
     */
    protected $_browsecatalogs;
    public function __construct(
        Context $context,
        BrowsecatalogsFactory $browsecatalogs
    ) {
        $this->_browsecatalogs = $browsecatalogs;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Browse Catalogs'));
        
        if ($this->getBrowsecatalogsCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'intesols.browsecatalogs.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getBrowsecatalogsCollection()
            );
            $this->setChild('pager', $pager);
            $this->getBrowsecatalogsCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getBrowsecatalogsCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 8;

        $browsecatalogs = $this->_browsecatalogs->create();
        $collection = $browsecatalogs->getCollection();
        $collection->addFieldToFilter('status','1');
        //$browsecatalogs->setOrder('browsecatalogs_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}