<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
	$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
	$_scopeConfig = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
	$price =  $_product->getFinalPrice(); //Your Price
	$formattedPrice = $priceHelper->currency($price, true, false);
	//echo "heelo".$_product->getData('is_sale');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$_product = $objectManager->get('Magento\Catalog\Model\Product')->load($_product->getId());
$specialLabel = $_product->getData('coming_soon');
//echo "(".$specialLabel.")";
?>
<?php 
$showPrice = $_scopeConfig->getValue('intesolstheme/itprice/price', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>
<?php if($_product->getTypeId() == 'simple'){ ?>
<div class="product-options-bottom <?php if($_product->getForSale() == 0){ ?>price-whrtobuy<?php } ?>">
<?php } ?>
<div class="box-tocart" style="display: none;">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
					   <div class="plus-minus-grp">
					   <a class="btn-qty plus" href="javascript:void(0);"><div class="qty-plus"> +</div></a>
					   <a class="btn-qty minus" href="javascript:void(0);"><div class="qty-minus">-</div></a>
					   </div>
            </div>
			<script type="text/javascript">
		require(['jquery','domReady!'],function($){
			$(".btn-qty").click(function (event) {
				var $button = $(this);
				var oldValue = $button.closest('.control').find("input#qty").val();
				var defaultValue = <?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>;
				if ($button.hasClass('plus')) {
					var newVal = parseFloat(oldValue) + 1;
				} else {
					if (oldValue > defaultValue) {
					    var newVal = parseFloat(oldValue) - 1;
					} else {
					    newVal = defaultValue;
					}
				}
				$button.closest('.control').find("input#qty").val(newVal);
				event.preventDefault();
			});

		});
        </script>
			 <div class="actions">
            <button type="submit"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
        </div>
        <?php endif; ?>
		<!--<div class="rrp-price">			
		<?php //echo $_product->getPriceInfo()->getPrice('final_price')->getAmount(); ?>
		<?php //echo gettype($_product->getPriceInfo()->getPrice('final_price')->getAmount()); ?>		
		<?php  echo "<span>RRP: </span>".$formattedPrice; ?>
		</div>-->
       
    </div>
</div>
<div class="nocart">
<div class="buyatcall">
<?php
//echo $attribute_string = $_product->getResource()->getAttribute('coming_soon')->getFrontend()->getValue($_product); 
 ?>
            <a href="javascript:void(0);" id="showresllerbtb" title="Where to Buy" class="action primary tocart">
                <span><?php echo "Where to Buy"; ?></span>
            </a>
</div>
</div>
<?php if($_product->getTypeId() == 'simple'){ ?>
</div>
<?php } ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>
<?php if ($_product->getTypeId() == "simple" && $_product->getForSale() == 1) { ?>
    <script>
        jQuery(window).load(function() {
            jQuery('.box-tocart').show();
            jQuery('.price-box').show();
            jQuery('.nocart').hide();
        });
    </script>
    <?php } ?>
<script>
jQuery(document).ready(function() {
	//jQuery('.price-box').css("display", "block");
	jQuery('#showresllerbtb').click(function(){
		setTimeout( function(){ 
			   var pageHeight = jQuery(document).height();
						jQuery('<div id="active-popup"></div>').insertBefore('body');
						jQuery('#active-popup').css("height", pageHeight);
						jQuery('.ressler-pop').show();
						jQuery('body').addClass('mpopup');
			}  , 10 );
		
	});
	});
</script>	
