<?php
/**
 * @category   Intesols
 * @package    Intesols_Browsecatalogs
 * @author     jaimin.patel@intesols.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Intesols\Browsecatalogs\Model\ResourceModel\Browsecatalogs;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'browsecatalogs_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Intesols\Browsecatalogs\Model\Browsecatalogs',
            'Intesols\Browsecatalogs\Model\ResourceModel\Browsecatalogs'
        );
    }
}