<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
<div class="ctontent">
<div class="success-block">
<i class="fa fa-check-circle" aria-hidden="true"></i>
<span class="meseg">
<p class="uper-meseg"><strong>Your order has been received</strong></p>
<p>Thank you for your purchase!</p>
</span>
</div>

<div class="ncontent">
	<p>Your order # is: <a href="<?php echo $block->escapeHtml($block->getViewOrderUrl()); ?>"><?php echo $block->escapeHtml($block->getOrderId()); ?></a></p>
	<p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
</div>
<div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
</div>


</div>
</div>
<?php 
$days = '5 days';
$estimated_date = date('Y-m-d', strtotime($days));
?>
<script>
    window.renderOptIn = function() {
        window.gapi.load('surveyoptin', function() {
            window.gapi.surveyoptin.render(
            {
                "merchant_id": 143723739,
                "order_id": "<?php echo $block->getOrder()->getIncrementId() ?>",
                "email": "<?php echo $block->getOrder()->getCustomerEmail() ?>",
                "delivery_country": "<?php echo $block->getOrder()->getShippingAddress()->getCountryId() ?>",
                "estimated_delivery_date": "<?php echo $estimated_date; ?>",
            });
        });
    }
</script>

<!--
    <?php if ($block->getOrderId()):?>
        <?php if ($block->getCanViewOrder()) :?>
            <p><?php echo __('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
        <?php  else :?>
            <p><?php echo __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
        <?php endif;?>
            <p><?php /* @escapeNotVerified */ echo __('We\'ll email you an order confirmation with details and tracking info.') ?></p>
    <?php endif;?>

    <?php echo $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?php /* @escapeNotVerified */ echo $block->getUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div> --> 
