<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct() ?>

<?php if (!$block->displayProductStockStatus()): ?>
	<div class="stock-label">Stock Status:</div>
    <?php if ($_product->isAvailable()): ?>
        <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
        </div>
    <?php else: ?>
        <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
            <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php 

if ($_product->getTypeId() == 'simple') {

if($_product->getLength1()) { 

$optionId = $_product->getLength1();   
 $attr = $_product->getResource()->getAttribute('length_1');
 if ($attr->usesSource()) {
    $optionText = $attr->getSource()->getOptionText($optionId);
 }
if(!empty($optionText)) {
?>
<div class="product attribute barcode">
    <strong class="type">Length</strong>    <div class="value"><?php  echo $optionText; ?></div>
</div>	
<?php } }  else {
	$optionId = $_product->getLength();   
 $attr = $_product->getResource()->getAttribute('length_1');
 if ($attr->usesSource()) {
    $optionText = $attr->getSource()->getOptionText($optionId);
 }
 if(!empty($optionText)) {
?>
<div class="product attribute barcode">
    <strong class="type">Length</strong>    <div class="value"><?php  echo $optionText; ?></div>
</div>
	
 <?php } } } ?>
