<?php
/**
 * @category   Intesols
 * @package    Intesols_Browsecatalogs
 * @author     jaimin.patel@intesols.com.au
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Intesols\Browsecatalogs\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Intesols\Browsecatalogs\Block\BrowsecatalogsView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_browsecatalogsview;

	public function __construct(
        Context $context,
        BrowsecatalogsView $browsecatalogsview
    ) {
        $this->_browsecatalogsview = $browsecatalogsview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_browsecatalogsview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
