<?php
/**
 * Copyright Â© 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Store switcher template
 *
 * @see \Magento\Store\Block\Store\Switcher
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$surl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<?php if (count($block->getGroups())>1): ?>
    <div class="switcher store switcher-store" id="switcher-store">
        <strong class="label switcher-label"><span><?php /* @escapeNotVerified */ echo __('Select Store') ?></span></strong>
        <div class="actions dropdown options switcher-options">
            <?php foreach ($block->getGroups() as $_group): ?><?php //if($_group->getName() == 'Norway') continue; ?>
                <?php if ($_group->getId() == $block->getCurrentGroupId()): ?>

                    <div class="action toggle switcher-trigger"
                         role="button"
                         tabindex="0"
                         data-mage-init='{"dropdown":{}}'
                         data-toggle="dropdown"
                         data-trigger-keypress-button="true"
                         id="switcher-store-trigger">
                        <strong>
                    <span><?php if($_group->getName() == 'US'){ ?>
                            <img src="<?php echo $surl; ?>alogic/US.jpg" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'Australia') {?>
                            <img src="<?php echo $surl; ?>alogic/aus.png" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'India') {?>
                            <img src="<?php echo $surl; ?>alogic/in.png" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'New Zealand') {?>
                            <img src="<?php echo $surl; ?>alogic/nz.png" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'France') {?>
                            <img src="<?php echo $surl; ?>alogic/france.jpg" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'Germany') {?>
                            <img src="<?php echo $surl; ?>alogic/germany-new.jpg" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'Singapore') {?>
                            <img src="<?php echo $surl; ?>alogic/SGP.jpg" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'UK') {?>
                            <img src="<?php echo $surl; ?>alogic/UK.png" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Sweden') {?>
                            <img src="<?php echo $surl; ?>alogic/swed.png" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Denmark') {?>
                            <img src="<?php echo $surl; ?>alogic/den.png" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Norway') {?>
                            <img src="<?php echo $surl; ?>alogic/norw.png" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Finland') {?>
                            <img src="<?php echo $surl; ?>alogic/fin.png" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Iceland') {?>
                            <img src="<?php echo $surl; ?>alogic/ice.png" style="width:16px;"/>
                        <?php } else if ($_group->getName() == 'Hong Kong') {?>
                            <img src="<?php echo $surl; ?>alogic/Hongkong.jpg" style="width:16px;"/>
			<?php } else if ($_group->getName() == 'Ireland') {?>
                            <img src="<?php echo $surl; ?>alogic/ireland.jpg" style="width:16px;"/>
                        <?php }  else  { ?>
                            <img src="<?php echo $surl; ?>alogic/us.ico" style="width:16px;"/>
                        <?php } ?>
                        <?php echo $block->escapeHtml($_group->getName()) ?></span>
                        </strong>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <ul class="dropdown switcher-dropdown" data-target="dropdown">
                <?php foreach ($block->getGroups() as $_group): ?><?php //if($_group->getName() == 'Norway') continue; ?>
                    <?php if (!($_group->getId() == $block->getCurrentGroupId())): ?>
                        <li class="switcher-option">
                            <a
                                data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_group->getDefaultStore()); ?>'>
                                <?php if($_group->getName() == 'US'){ ?>
                                    <img src="<?php echo $surl; ?>alogic/us.ico" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'Australia') {?>
                                    <img src="<?php echo $surl; ?>alogic/aus.png" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'India') {?>
                                    <img src="<?php echo $surl; ?>alogic/in.png" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'New Zealand') {?>
                                    <img src="<?php echo $surl; ?>alogic/nz.png" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'France') {?>
                                    <img src="<?php echo $surl; ?>alogic/france.jpg" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'Germany') {?>
                                    <img src="<?php echo $surl; ?>alogic/germany-new.jpg" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'Singapore') {?>
                                    <img src="<?php echo $surl; ?>alogic/SGP.jpg" style="width:16px;"/>
				<?php } else if ($_group->getName() == 'Sweden') {?>
                                    <img src="<?php echo $surl; ?>alogic/swed.png" style="width:16px;"/>
				<?php } else if ($_group->getName() == 'Denmark') {?>
	                            <img src="<?php echo $surl; ?>alogic/den.png" style="width:16px;"/>
				<?php } else if ($_group->getName() == 'Norway') {?>
	                            <img src="<?php echo $surl; ?>alogic/norw.png" style="width:16px;"/>
				<?php } else if ($_group->getName() == 'Finland') {?>
	                            <img src="<?php echo $surl; ?>alogic/fin.png" style="width:16px;"/>
				<?php } else if ($_group->getName() == 'Iceland') {?>
	                            <img src="<?php echo $surl; ?>alogic/ice.png" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'UK') {?>
                                    <img src="<?php echo $surl; ?>alogic/UK.png" style="width:16px;"/>
                                <?php } else if ($_group->getName() == 'Hong Kong') {?>
                                    <img src="<?php echo $surl; ?>alogic/Hongkong.jpg" style="width:16px;"/>
								<?php } else if ($_group->getName() == 'Ireland') {?>
                                    <img src="<?php echo $surl; ?>alogic/ireland.jpg" style="width:16px;"/>
                                <?php }  else  { ?>

                                    <img src="<?php echo $surl; ?>alogic/us.ico" style="width:16px;"/>
                                <?php } ?>
                                <?php echo $block->escapeHtml($_group->getName()) ?>
                            </a>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ul>
        </div>
    </div>
    <script>
        require([
            'jquery',
            'mage/cookies',
            'domReady!'
        ], function($) {
            $(".switcher-option").click(function(){
                $.cookie("geo_preference", "", { path: '/' });
            });
        });
    </script>
<?php endif; ?>
