<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currentStore = $storeManager->getStore();
$current_category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
if ($current_category && !($current_category->getLevel() == 4 && $current_category->getChildren())) {
    echo "<h2>" . $current_category->getName() . "</h2>";
}

$currencyCode = $storeManager->getStore()->getCurrentCurrencyCode();
$currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();

/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
$_productCollection = $block->getProductCollection();
//$_helper = $this->helper('Magento\Catalog\Helper\Output');
$attachmentBlock = $objectManager->create('\MageWorx\Downloads\Block\Catalog\Product\Attachments');
?>

<?php
function truncate($string, $length, $stopanywhere = false)
{
    //truncates a string to a certain char length, stopping on a word if not specified otherwise.
    if (strlen($string) > $length) {
        //limit hit!
        $string = substr($string, 0, ($length - 3));
        if ($stopanywhere) {
            //stop anywhere
            $string .= '...';
        } else {
            //stop on a word.
            $string = substr($string, 0, strrpos($string, ' ')) . '...';
        }
    }
    return $string;
}
$viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>

<div class="main-cat-category">
    <div class="products wrapper grid products-grid">

        <?php $iterator = 1; ?>
        <ol class="subcat-view products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */
                echo ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="subcat-pro item gggggggg">
                    <div class="search-product-image">
                        <?php
                        //$pos = $block->getPositioned();
                        if ($block->getMode() == 'grid') {
                            $viewMode = 'grid';
                            $image = 'category_page_grid';
                            $showDescription = false;
                            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
                        } else {
                            $viewMode = 'list';
                            $image = 'category_page_list';
                            $showDescription = true;
                            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
                        }
                        ?>
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <a href="<?php /* @escapeNotVerified */
                        echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                    </div>
                    <div class="ptitle">
                        <a href="<?php echo $_product->getProductUrl() ?>" class="ptext">
                            <?php echo $_product->getName(); ?>
                        </a>
                    </div>                    
                    <?php if ($_product->getShowForSale() == 1 && $_product->getForSale() == 1) { ?>
                        <div class="cate-pro-price">
                            <?php /* @escapeNotVerified */
                            echo $block->getProductPrice($_product) ?>

			   <?php 
				//if($_product->getTypeId() == 'configurable'){
					//$nprice = round($_product->getPriceInfo()->getPrice('regular_price')->getAmount());
					//echo $currencySymbol. $nprice;
				//}
			   ?>
                        </div>
                    <?php } else { ?>
                        <div class="nocart">
                            <div class="buyatcall">
                <?php if($_product->getData('coming_soon')) { ?>
                        <a href="javascript:void(0);" title="Coming Soon" class="action primary tocart">
                                <span>Coming Soon</span>
                    </a>
                            <?php }else{ ?>
                                                <a href="javascript:void(0);" id="showresllerbtb<?php echo $_product->getId(); ?>" title="Where to Buy" class="action primary tocart popuptrigger">
                                                
                                                <span><?php echo "Where to Buy"; ?></span>
                                            </a>
                                            <?php } ?>   
                                
                                <?php
                                $objectManager1 = \Magento\Framework\App\ObjectManager::getInstance();
                                $__modelDistributorFactory = $objectManager1->create('Intesols\Distributor\Model\DistributorFactory');
                                //echo "<span style='display:none'>".$_product->getReseller()."</span>";
                                $nationalIdArray = explode(',', $_product->getData('national_retailer'));
                                $resellerIdArray = explode(',', $_product->getData('reseller'));
                                $distributorIdArray = explode(',', $_product->getDistributor());

                                $distributorModel = $__modelDistributorFactory->create();
                                $resellerModel = $distributorModel->getCollection()->addFieldToFilter('id', array('in' => $resellerIdArray));
                                $nationalModel = $distributorModel->getCollection()->addFieldToFilter('id', array('in' => $nationalIdArray));
                                $distributorModel = $distributorModel->getCollection()->addFieldToFilter('id', array('in' => $distributorIdArray));
                                $productTypeInstance = $_product->getTypeInstance();
                                if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
                                    $usedProducts = $productTypeInstance->getUsedProducts($_product);
                                    $prod_sku = "";
                                    foreach ($usedProducts as $child) {
                                        $prod_sku = $child->getSku();
                                        break;
                                    }
                                }
                                ?>
                                <div id="popup-container" class="ressler-pop <?php echo $_product->getSku(); ?>">
                                    <a class="close"><i class="fa fa-times" aria-hidden="true"></i></a>
                                    <div id="popup-window">
                                        <div class="modal-content">
                                            <div class="wdpu-head">
                                                <div class="wdpu-title">
                                                    <a href="javascript:void(0);"><img
                                                                src="<?php echo $block->getUrl() . 'pub/media/Reseller-icon.png'; ?>"
                                                                alt="Resellers"/></a>
                                                </div>
                                                <div class="wdpu-subtitle"><span>View Resellers</span></div>
                                            </div>
                                            <div class="allresler">
                                                <div id="reseller-container" class="">
                                                    <ul>
                                                        <?php foreach ($nationalModel

                                                                       as $reseller) {
                                                            $reseller_url = $reseller->getSearchString();
                                                            //$reseller_url = str_replace("{{sku}}",$first_sku,$reseller_url);
                                                            ?>
                                                            <?php if (isset($prod_sku)) { ?>
                                                                <li>
                                                                    <a target="_blank"
                                                                       href="<?php echo str_replace('{{sku}}', $prod_sku, $reseller_url); ?>"><img
                                                                                width="125" height="100"
                                                                                src="<?php echo $this->getUrl('pub/media') . $reseller->getLogo() ?>"
                                                                                alt="<?php echo $reseller->getName() ?>"/></a>
                                                                </li>
                                                            <?php } ?>
                                                            <?php
                                                        }
                                                        foreach ($resellerModel as $reseller) {
                                                            $reseller_url = $reseller->getSearchString();

                                                            //$reseller_url = str_replace("{{sku}}",$first_sku,$reseller_url);
                                                            ?>
                                                            <?php if (isset($prod_sku)) { ?>
                                                                <li>
                                                                    <a target="_blank"
                                                                       href="<?php echo str_replace('{{sku}}', $prod_sku, $reseller_url); ?>"><img
                                                                                width="125" height="100"
                                                                                src="<?php echo $this->getUrl('pub/media') . $reseller->getLogo() ?>"
                                                                                alt="<?php echo $reseller->getName() ?>"/></a>
                                                                </li>
                                                            <?php } ?>
                                                        <?php } ?>
                                                    </ul>


                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    <?php } ?>

                    <div class="lastBC">

                        <a title="Add to Cart" class="action tocart primary"
                           href="<?php echo $_product->getProductUrl() ?>">
                            <span>View Details</span>
                        </a>
                        <div style="display:none;">
                            <?php echo $block->getProductDetailsHtml($_product); ?>
                        </div>


                        <?php //echo $block->getReviewsSummaryHtml($_product, "sort", true); ?>

                        <div class="psku"> <?php echo $_product->getSku(); ?> </div>

                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>

</div>
    <script type="text/javascript">
        jQuery(window).load(function () {
            jQuery(".level2.activeis-active").parent().parent().addClass("bbbbbbbb");
            jQuery(".bbbbbbbb .expanded").html('<i class="fa fa-angle-down"></i>');
        });
    </script>
    <script type="text/javascript">
        require(['jquery', 'domReady!'], function ($) {
            $(".btn-qty").click(function (event) {
                var $button = $(this);
                var oldValue = $button.closest('.control').find(".qty").val();
                var defaultValue = <?php /* @escapeNotVerified */ echo 1 ?>;
                if ($button.hasClass('plus')) {
                    var newVal = parseFloat(oldValue) + 1;
                } else {
                    if (oldValue > defaultValue) {
                        var newVal = parseFloat(oldValue) - 1;
                    } else {
                        newVal = defaultValue;
                    }
                }
                $button.closest('.control').find(".qty").val(newVal);
                event.preventDefault();
            });
        });
    </script>
<script>
        jQuery(window).load(function () {
            setTimeout(function () {
                var dp = 0;
                jQuery(".main-cat-category .product-item").each(function () {
                    var hs = jQuery(this).height();
                    if (hs > dp) {
                        dp = hs;
                    }
                });
                var msss = dp + parseInt(19);

                jQuery('.main-cat-category .product-item').css('height', msss + 'px');
                jQuery('.lastBC').css('position', 'absolute');
                jQuery('.lastBC').css('bottom', '20px');
            }, 1000);
        });

        jQuery(window).resize(function () {
            var dp = 0;
            jQuery(".main-cat-category .product-item").each(function () {
                jQuery('.main-cat-category .product-item').css('height', '');
                var hs = jQuery(this).height();
                if (hs > dp) {
                    dp = hs;
                }
            });
            var msss = dp + parseInt(19);
            jQuery('.main-cat-category .product-item').css('height', dp + 'px');
        });
    </script>

<?php /* popup Script */ ?>
    <script>
        jQuery(document).ready(function () {
	    //jQuery('span.price-label').css("display", "block");
	    //jQuery('span.price-label').attr('style','display: block !important');
	    jQuery('.price-box .old-price').removeClass('no-display').addClass('clearfix');
	    jQuery('.old-price .price').wrap('<del></del>');
		console.log(jQuery('.old-price .price').length);

            jQuery('#popup-container a.close').click(function () {
                jQuery('#popup-container').fadeOut();
                jQuery('#active-popup').fadeOut();
                jQuery('#active-popup').hide();
                jQuery('.wrap-unwrap').hide();
                jQuery('.ressler-pop').hide();
                jQuery('body').removeClass('mpopup');
            });
            jQuery('.ressler-pop a.close').click(function () {
                jQuery('.ressler-pop').fadeOut();
                jQuery('#active-popup').fadeOut();
                jQuery('#active-popup').hide();
                jQuery('.wrap-unwrap').hide();
                jQuery('.ressler-pop').hide();
                jQuery('body').removeClass('mpopup');
            });

            jQuery('#showdist').click(function () {
                setTimeout(function () {
                    var pageHeight = jQuery(document).height();
                    jQuery('<div id="active-popup"></div>').insertBefore('body');
                    jQuery('#active-popup').css("height", pageHeight);
                    jQuery('.distributors-pop').show();
                    jQuery('body').addClass('mpopup');
                }, 10);

            });
            // jQuery('#showresller').click(function(){
            // setTimeout( function(){
            // var pageHeight = jQuery(document).height();
            // jQuery('<div id="active-popup"></div>').insertBefore('body');
            // jQuery('#active-popup').css("height", pageHeight);
            // jQuery('.ressler-pop').show();
            // jQuery('body').addClass('mpopup');
            // }  , 10 );

            // });

            jQuery('#active-popup').on("click", "a", function () {
                console.log("clicked");
                jQuery('#popup-container').fadeOut();
                jQuery('#active-popup').fadeOut();
                //jQuery('#active-popup').remove();
                jQuery('body').removeClass('mpopup');
                jQuery('.ressler-pop').hide();
                jQuery('#active-popup').fadeOut();
                jQuery('.wrap-unwrap').fadeOut();
                //jQuery('#active-popup').remove();
                jQuery('body').removeClass('mpopup');

            });


        });

        require(['jquery'], function ($) {
            jQuery(document).ready(function () {
                jQuery('body').click(function () {
                    jQuery('#popup-container').fadeOut();
                    jQuery('#active-popup').fadeOut();
                    //jQuery('#active-popup').remove();
                    jQuery('body').removeClass('mpopup');
                    //jQuery('.ressler-pop').fadeOut();
                });
            });


        });


    </script>
    <script>
        jQuery('.price-box').css("display", "block");
       // jQuery('.price-box .old-price').toggleClass('no-display').toggleClass('clearfix');
        
        jQuery(document).on('click', 'a.popuptrigger', function () {
            var test = jQuery(this).siblings('.ressler-pop').wrap('<div id="active-popup" class="wrap-unwrap"></div>');
            var str = test.parent().html();
            // console.log(str);
            jQuery(this).siblings('.ressler-pop').html(str);
            jQuery(this).siblings('.wrap-unwrap').css("height", jQuery(document).height());
            jQuery(this).siblings('.wrap-unwrap').css("position", 'fixed');
            jQuery(this).siblings('.wrap-unwrap').show();
            jQuery('body').addClass('mpopup');
            jQuery(this).siblings('div').children('.ressler-pop').show();
            console.log(jQuery(this).siblings('.ressler-pop'));
        });
    </script>
<?php /* popup Script */ ?>




