<?php 
$_items     =   $block->getReviewsCollection()->getItems();
$format     =   $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
$review     =   array();
$urlInterface = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Framework\UrlInterface');

$mc = '';
$md = '';
$mm = 0;
foreach ($_items as $_review){
	
	if (count($_review->getRatingVotes())) {
            foreach ($_review->getRatingVotes() as $_vote) {
                $rating_vote =  $_vote->getPercent();
				$md = $rating_vote / 20;
				$mc = $mc + $md;
                $rating_code =  $block->escapeHtml($_vote->getRatingCode());
            }
        } else {
            $rating_vote = 0;
            $rating_code = '';
        }
		
		$mm++;
} 
$rates = $mc;
$counts = $mm;
$c = $counts; ?>
<span class="rev-title">Reviews </span>
<?php

if (count($_items)) {
    $i=0; ?>
	<ol class="items review-items">
    <?php foreach ($_items as $_review){

        if (count($_review->getRatingVotes())) {
            foreach ($_review->getRatingVotes() as $_vote) {
                $rating_vote =  $_vote->getPercent();
                $rating_code =  $block->escapeHtml($_vote->getRatingCode());
            }
        } else {
            $rating_vote = 0;
            $rating_code = '';
        }
  
	?>
	
	<li class="item review-item rev-item">
               
                        <div class="review-ratings">
                                        <div class="rating-summary item rev-summary">
                        <div class="rating-result" title="<?php echo $rating_vote; ?>%">
	                        <meta content="1">
	                        <meta content="100">
                            <span style="width:<?php echo $rating_vote; ?>%;">
                                <span><?php echo $rating_vote; ?>%</span>
                            </span>
                        </div>
                       </div>
                                        </div>
                                <div class="review-content"><?php echo $block->escapeHtml($_review->getDetail()); ?></div>
               
            </li>

<?php $i++;
if($i==2) break;
} ?>
</ol>
<div class="rev-actions">
<a class="rev-view" href="<?php echo $urlInterface->getCurrentUrl();?>#product-review-container"><span>Click here for more Reviews</span></a>
</div>

<?php } else {  ?>
	<?php 
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
/* Get base url with index When index.php enable at Url */
$baseUrl = $storeManager->getStore()->getBaseUrl();
/* Result  http://www.example.com/ or http://www.example.com/index.php  depends SEo rewite settng*/
/* it always give the URL without Index.php either index.php enable for Url */ 
$baseUrlWithOutIndexPhp = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
// $baseUrl  result = http://example.com/
 
/* It is give url with index.php whenever  seo rewrite not enable mean when  Index.php show at Url  */
 
$linkUrl= $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
 
 /* $linkUrl  result = http://example.com/index.php/
 whenever  seo rewrite not enable mean when  Index.php show at Url
 
 but when  SEO Rewrite enabled
 
 Then it show result = http://example.com/
 
 */
 
$statiContenteUrl =$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_STATIC);
/* Result $statiContenteUrl = http://example.com/pub/static/version1507042743/
 In this part  version1507042743 is 1507042743 static content version which dynamcically created
*/
 
$mediaUrl =  $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
	
	?>
<div class="rev-actions">
<a class="rev-view" href="<?php echo $urlInterface->getCurrentUrl();?>#review-form"> <img src="<?php echo $mediaUrl; ?>gstar.png" /></a>
</div>	
<?php } ?>

<?php 
/* $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$reviewFactory = $objectManager->create('Magento\Review\Model\Review');

$storeId = $this->_storeManager->getStore()->getId();
$reviewFactory->getEntitySummary($product, $storeId);

echo $ratingSummary = $product->getRatingSummary()->getRatingSummary(); */ ?> 

